### ISSUE TITLE
[stream_video_flutter] It is not possible to run application at all on emulator 

### ISSUE THREAD

**Issue by Mounix99** [GetStream/stream-video-flutter#518]
I'm trying to run app in any mode on emulator and it fails cause directly stream_video_flutter , I did'n found any info in docs about debugging on emulator. On iOS emulator works as expected problem only on Android.

```
W/flutter.testing(12790): type=1400 audit(0.0:96): avc:  denied  { read } for  name="max_map_count" dev="proc" ino=101456 scontext=u:r:untrusted_app:s0:c182,c256,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=io.hoopit.app.android.flutter.testing
W/flutter.testing(12790): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (unsupported,test-api, reflection, allowed)
W/flutter.testing(12790): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (unsupported, reflection, allowed)
W/flutter.testing(12790): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (unsupported, reflection, allowed)
W/flutter.testing(12790): Accessing hidden method Landroid/util/LongArray;->get(I)J (unsupported, reflection, allowed)
W/flutter.testing(12790): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (unsupported, reflection, allowed)
W/FlutterWebRTCPlugin(12790): audioFocusChangeListener [Speakerphone(name=Speakerphone)] Speakerphone(name=Speakerphone)
W/flutter.testing(12790): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (unsupported, reflection, allowed)
W/flutter.testing(12790): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (unsupported, reflection, allowed)
E/AndroidRuntime(12790): FATAL EXCEPTION: main
E/AndroidRuntime(12790): Process: io.hoopit.app.android.flutter.testing, PID: 12790
E/AndroidRuntime(12790): java.lang.SecurityException: io.hoopit.app.android.flutter.testing: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/AndroidRuntime(12790): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/AndroidRuntime(12790): 	at android.os.Parcel.createException(Parcel.java:3041)
E/AndroidRuntime(12790): 	at android.os.Parcel.readException(Parcel.java:3024)
E/AndroidRuntime(12790): 	at android.os.Parcel.readException(Parcel.java:2966)
E/AndroidRuntime(12790): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
E/AndroidRuntime(12790): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
E/AndroidRuntime(12790): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
E/AndroidRuntime(12790): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
E/AndroidRuntime(12790): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
E/AndroidRuntime(12790): 	at io.getstream.video.flutter.background.stream_video_flutter_background.service.utils.AndroidUtilsKt$registerReceiverAsFlow$1.invokeSuspend(AndroidUtils.kt:36)
E/AndroidRuntime(12790): 	at io.getstream.video.flutter.background.stream_video_flutter_background.service.utils.AndroidUtilsKt$registerReceiverAsFlow$1.invoke(Unknown Source:8)
E/AndroidRuntime(12790): 	at io.getstream.video.flutter.background.stream_video_flutter_background.service.utils.AndroidUtilsKt$registerReceiverAsFlow$1.invoke(Unknown Source:4)
E/AndroidRuntime(12790): 	at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo$suspendImpl(Builders.kt:320)
E/AndroidRuntime(12790): 	at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo(Unknown Source:0)
E/AndroidRuntime(12790): 	at kotlinx.coroutines.flow.CallbackFlowBuilder.collectTo(Builders.kt:334)
E/AndroidRuntime(12790): 	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
E/AndroidRuntime(12790): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(12790): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(12790): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(12790): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(12790): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(12790): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(12790): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(12790): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12790): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(12790): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/AndroidRuntime(12790): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8e79d0b, Dispatchers.Main]
E/AndroidRuntime(12790): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(12790): 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13908)
E/AndroidRuntime(12790): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
E/AndroidRuntime(12790): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
E/AndroidRuntime(12790): 	at android.os.Binder.execTransactInternal(Binder.java:1339)
E/AndroidRuntime(12790): 	at android.os.Binder.execTransact(Binder.java:1275)
E/AndroidRuntime(12790): 
Lost connection to device.
```

If there is no option to run on emulator maybe there is a way to disable all requests to speakers and so on

**Comment by deven98** [comment]
Hey @Mounix99 👋 

Does this problem still persist with the latest version of the package?

**Comment by Mounix99** [comment]
@deven98 Hey, unfortunately still the same situation. Attaching full logs

**Comment by Brazol** [comment]
Hi @Mounix99, this issue should already be fixed with the latest release. Feel free to reopen it if it persists.
